### ISSUE TITLE
issue: buildUrl not found in

### ISSUE THREAD

**Issue by mfidalgo-RatedPower** [ctrf-io/mocha-ctrf-json-reporter#10]
I miss 'buildUrl' in the [types](https://github.com/ctrf-io/mocha-ctrf-json-reporter/blob/28a0eaaf3040db62863f1f4c0ccce84c68486c5d/types/ctrf.d.ts#L50-L59) so that it can be used later by https://github.com/ctrf-io/slack-ctrf

**Comment by Ma11hewThomas** [comment]
Hello, you might be our first user of mocha + slack! 

Thanks for reporting this, it's fixed in v0.0.6
